### ISSUE TITLE
Fluentd v0.14.0

### ISSUE THREAD

**Issue by Raznak** [bitsofinfo/fluentd-modsecurity#1]
Hello,

there is an error with Fluentd version 0.14.0

Fix:
Modifier le fichier:
out_modsecurity-audit-format.rb

Ligne 26:
- Fluent::Engine.emit(@tag, time, modsecRecord)
- router.emit(@tag, time, modsecRecord)

**Comment by bitsofinfo** [comment]
Can you please submit a pull request with the fix? Then I will merge it in.

thanks

**Comment by Raznak** [comment]
Done

**Comment by bitsofinfo** [comment]
There is no pull request submitted.

**Comment by Raznak** [comment]
Sorry, I just done it.

**Comment by bitsofinfo** [comment]
see https://github.com/bitsofinfo/fluentd-modsecurity/pull/2#issuecomment-224641815
